# Generated by Django 5.1.6 on 2025-04-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EducationalModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.PositiveIntegerField(
                        unique=True, verbose_name="Порядковый номер"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, verbose_name="Статус публикации"
                    ),
                ),
            ],
            options={
                "verbose_name": "Образовательный модуль",
                "verbose_name_plural": "Образовательные модули",
                "ordering": ["order_number"],
            },
        ),
    ]
