# Generated by Django 5.1.6 on 2025-04-09 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("education_modules", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EducationalModule",
            new_name="EducationModule",
        ),
    ]
