# Generated by Django 5.1.6 on 2025-04-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education_modules", "0002_rename_educationalmodule_educationmodule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="educationmodule",
            name="order_number",
            field=models.PositiveIntegerField(verbose_name="Порядковый номер"),
        ),
    ]
